include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: false
    no_runtimeType_toString: false
    prefer_const_constructors: false
    prefer_initializing_formals: false
    prefer_const_constructors_in_immutables: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
